### ISSUE TITLE
Add a deploy to Cloud Run button

### ISSUE THREAD

**Issue by dosco** [dosco/graphjin#118]
**What would you like to be added**:

I'd like a deploy to Google Cloud Run button added to README.md.
https://github.com/GoogleCloudPlatform/cloud-run-button

**Why is this needed**:

Easier for people to try out Super Graph

**Comment by kpbird** [comment]
@dosco 

I tried to add cloud run button with the following URL but the issue is in docker file where it can't COPY config from parent directory because following URL run `docker build` from `internal/serv/tmpl` in order to solve the problem  `docker build` needs to run from the root directory with `-f` command. there is no way we can ask dploy.cloud.run to run docker build from the root and use `/internal/serv/templ` to find `cloudbuild.yaml`

`https://deploy.cloud.run?git_repo=https://github.com/dosco/super-graph&revision=master&dir=/internal/serv/tmpl`

Is it possible to move `cloudbuild.yaml` to root?

**Comment by dosco** [comment]
The `cloudbuild.yml` in `/internal/serv/templ` is a template file to be used by the `./super-graph new <app_name>` command  to create a new Super Graph app. You'll have to copy it to the root and remove the template stuff in there `{{}}`.
