### ISSUE TITLE
Allowed subscriptions not being saved during development

### ISSUE THREAD

**Issue by diegosz** [dosco/graphjin#187]
Hi, I notice that the subscriptions were not being saved in the allowed queries/fragments folders, so was going to send a pull request for the file `core/subs.go`:

```go
diff --git a/core/subs.go b/core/subs.go
index ef0a531..bffdb8e 100644
--- a/core/subs.go
+++ b/core/subs.go
@@ -143,6 +143,12 @@ func (gj *GraphJin) newSub(c context.Context, s *sub, query string, vars json.Ra
                return err
        }
 
+       if gj.allowList != nil {
+               if err := gj.allowList.Set(vars, query); err != nil {
+                       return err
+               }
+       }
+
        if len(s.q.st.md.Params()) != 0 {
                s.q.st.sql = renderSubWrap(s.q.st, gj.schema.DBType())
        }
```

With that patch it works fine, and it saves the subscriptions as allowed.

But notice that when in production that patch in `core/subs.go` and also line 233 in `core/core.go` are also running, so even all the queries are already compiled as prepared statements they are being saved again in the allowed folders.

Think core.Config needs a new field like `Production` or `CreateAllowList` so the allowed creation could be omitted during production.

Any comments?

Cheers

**Comment by dosco** [comment]
Great catch I must have miss that in some refactor. I feel adding a `Production` flag to core would be the best option so we can in future make other choices based off that instead of having to add config flags for each one. It should maybe not be a config value and instead be a field on the `GraphJin` struct and it's initial value set to `GO_ENV == "production"`

**Comment by diegosz** [comment]
Great, many thanks it's working perfect.
