### ISSUE TITLE
Question abourt SQL injection?

### ISSUE THREAD

**Issue by yuanxuzhang** [dosco/graphjin#214]
First of all, graphjin was amazing project.
Right now i am not familiar with golang, i wonder was there sql injection consider soultion in the SQL complier model?
thx.

**Comment by dosco** [comment]
Could you reframe that I don't quite understand the question? If your asking about security from an sql injection attack then yes since in production mode the SQL query is compiled into an prepared statement and the variables are only passed as parameters to the statement so no sql inject is possible https://medium.com/@jaredablon_31568/how-to-prevent-sql-injection-vulnerabilities-how-prepared-statements-work-f492c369614f#:~:text=A%20prepared%20statement%20is%20a,safely%2C%20preventing%20SQL%20Injection%20vulnerabilities.

**Comment by yuanxuzhang** [comment]
I mean about security from an sql injection attack. 
Appreciate.
