### ISSUE TITLE
Two different queries return the same subscription

### ISSUE THREAD

**Issue by slava-vishnyakov** [dosco/graphjin#287]
I have this subscription:

```graphql
subscription newSubscriptions {
  subscriptions(where: {user_id: {eq: "8020A665-6CC6-43DE-81FF-3498C0B9D9F5"}}) {
    channel {
      name
    }
    unread_count
  }
}
```

I open one browser with this subscription. 

Then I open another one with a similar subscription, but a different user_id:

```graphql
subscription newSubscriptions {
  subscriptions(where: {user_id: {eq: "703CD8B3-9600-46B1-AE97-E02A3085A097"}}) {
    channel {
      name
    }
    unread_count
  }
}
```

Now, just like in #284 the second user doesn't get anything, but now I change the data for the first user...

...and both users get the same data in their subscriptions! 

So, basically, the second user got the data that was intended for the first user. 

This is a huge security issue.

**Comment by slava-vishnyakov** [comment]
The data for the second user isn't even monitored (i.e. the subscription never returns anything when I change the data intended for the second user).

**Comment by dosco** [comment]
I'll take a look.

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/graphjin/commit/175397969e5b94d872985aa2db5523c0ed1a250f

**Comment by slava-vishnyakov** [comment]
Thank you!

**Comment by dosco** [comment]
I had some time to think about this the reason for the behaviour you initially saw is because you didn't use variables. If you don't use variables then the subscription is based on the name of the query `newSubscriptions` so the first time you created a subscription it was registered then everyone else you subscribed with the same query name got the same result. This is not a security issue since the query is a public query and not limited by `$user_id` etc.

If you want each subscriber to get his own information then you have to use variables. In the below case the user_id value from the authentication token will be used.

```
subscription newSubscriptions {
  subscriptions(where: {user_id: {eq: $user_id }}) {
    channel {
      name
    }
    unread_count
  }
}
``
